```{r}
# Loading all necessary packages
library(tidyverse)
library(dplyr)
library(tidymodels)
library(readr)
library(kknn)
library(janitor)
library(ISLR)
library(discrim)
library(poissonreg)
library(glmnet)
library(corrr)
library(corrplot)
library(randomForest)
library(xgboost)
library(rpart.plot)
library(vip)
library(ranger)
# Assigning the data to a variable
pokemon <- read_csv("data/pokemon.csv")
tidymodels_prefer()
set.seed(0124)
```

```{r}
# Calling head() to see the first few rows
head(pokemon)
```


```{r}
# Calling dim() to see how many rows and columns
dim(pokemon)
```

```{r}
# Selecting only the variables we want
pokemon <- pokemon %>% 
  select(c("abilities", "attack", "base_happiness",  "base_total", "capture_rate", "defense", "experience_growth", "height_m", "percentage_male", "hp", "name", "sp_attack", "sp_defense", "speed", "type1", "weight_kg", "generation", "is_legendary")) %>% 
  clean_names()
head(pokemon)
```

```{r}
# summary stats
pokemon %>% 
  summary()

# missing values?
colSums(is.na(pokemon))
```

```{r}
# capture rate should not be a character
library(dplyr)
filter(pokemon, capture_rate %in% c("30 (Meteorite)255 (Core)"))
pokemon[pokemon$name=="Minior", "capture_rate"] <- "30"
pokemon$capture_rate <- as.integer(pokemon$capture_rate)
# I chose 30 because the capture rate only rises to 255 if you break its shell
filter(pokemon, name %in% c("Minior"))
```

```{r}
generation_levels <- c(1,2,3,4,5,6,7)
pokemon$generation <- factor(pokemon$generation, levels=generation_levels)
# MAKE IS_LEGENDARY A FACTOR
```

```{r}
pokemon %>% 
  summary()
```

```{r}
library(tidytext)
```

```{r}
test <- pokemon$abilities %>% 
  str_split(pattern = "', '") #%>% 
  # str_extract_all(string = ., pattern = "\\w+", simplify = TRUE)
  # map(str_extract_all(string = ., pattern = "\\w+", simplify = TRUE))
all_abilities <- test %>% map(~ str_replace_all(string = ., pattern = "[[:punct:]]", "")) %>% 
  unlist() %>% as.factor() %>% 
  data.frame(abilities = .)

all_abilities %>% group_by(abilities) %>% summarise(count = n(), capture_rate = mean(capture_rate)) %>% 
  arrange(desc(count)) %>% View()
  
#ggplot(data = tibble(all_abilities)) +
 # geom_bar(aes(x = all_abilities))
```

```{r}
pokemon_copy <- pokemon
pokemon_copy$abilities <- pokemon_copy$abilities %>% 
  str_split(pattern = "', '") %>% 
  map(~ str_replace_all(string = ., pattern = "[[:punct:]]", ""))

#tidy_abilities <- pokemon_copy %>% 
#  unnest_tokens(words, abilities)

pokemon_copy2 <- pokemon_copy %>% 
  unnest() 

pokemon_copy2 %>% group_by(abilities) %>%  summarise(count = n(), capture_rate = mean(capture_rate)) %>% 
  arrange(desc(count)) %>% View()
```

```{r}
library(dplyr)

pokemon_abilities_grouped <- pokemon_copy2 %>% 
  group_by(abilities)

pokemon_abilities_grouped %>% 
  summarise(
    capture_rate = mean(capture_rate)
  ) %>% 
  arrange(desc(capture_rate))

```



```{r}
mean(pokemon_copy2$capture_rate)
```

```{r}
# making boolean columns for if a pokemon has the top 5 most apparent abilities
pokemon_copy3 <- pokemon

sturdy <- "Sturdy"
pokemon_copy4 <- pokemon %>% 
  mutate(has_sturdy = if_else(grepl("Sturdy", pokemon$abilities), 1, 0)) %>% 
  mutate(has_swift_swim = if_else(grepl("Swift Swim", pokemon$abilities), 1, 0)) %>% 
  mutate(has_keen_eye = if_else(grepl("Keen Eye", pokemon$abilities), 1, 0)) %>% 
  mutate(has_chlorophyll = if_else(grepl("Chlorophyll", pokemon$abilities), 1, 0)) %>% 
  mutate(has_levitate = if_else(grepl("Levitate", pokemon$abilities), 1, 0))

sum(pokemon_copy4$has_sturdy)
sum(pokemon_copy4$has_swift_swim)
sum(pokemon_copy4$has_keen_eye)
sum(pokemon_copy4$has_chlorophyll)
sum(pokemon_copy4$has_levitate)

write_csv(pokemon_copy4, "pokemon_final.csv")
```

```{r}
pokemon_data <- read_csv("pokemon_final.csv")
head(pokemon_data)
```

```{r}
# Changing categorical predictors to factors
pokemon_data$type1 <- as.factor(pokemon_data$type1)
pokemon_data$generation <- as.factor(pokemon_data$generation)
pokemon_data$is_legendary <- as.factor(pokemon_data$is_legendary)
pokemon_data$has_sturdy <- as.factor(pokemon_data$has_sturdy)
pokemon_data$has_swift_swim <- as.factor(pokemon_data$has_swift_swim)
pokemon_data$has_keen_eye <- as.factor(pokemon_data$has_keen_eye)
pokemon_data$has_chlorophyll <- as.factor(pokemon_data$has_chlorophyll)
pokemon_data$has_levitate <- as.factor(pokemon_data$has_levitate)
```

```{r}
ggplot(pokemon_data, aes(capture_rate)) + 
  geom_bar(aes(fill = is_legendary))

ggplot(pokemon_data, aes(capture_rate)) + 
  geom_bar(aes(fill = generation))
```


```{r}
summary(pokemon_data)
```

```{r}
# Splitting the data
pokemon_split <- initial_split(pokemon_data, prop = 0.7, strata = capture_rate)
pokemon_train <- training(pokemon_split)
pokemon_test <- testing(pokemon_split)
```

```{r}
# Creating recipe
pokemon_recipe <- recipe(capture_rate ~ base_total + base_happiness + experience_growth + height_m + percentage_male + weight_kg + type1 + generation + is_legendary + has_sturdy + has_swift_swim + has_keen_eye + has_chlorophyll + has_levitate, data = pokemon_train) %>% 
  # imputing percentage male
  step_impute_linear(percentage_male, impute_with = imp_vars(base_total, base_happiness, experience_growth, type1, generation, is_legendary, has_sturdy, has_swift_swim, has_keen_eye, has_chlorophyll, has_levitate)) %>% 
  # imputing height
  step_impute_linear(height_m, impute_with = imp_vars(base_total, base_happiness, experience_growth, type1, generation, is_legendary, has_sturdy, has_swift_swim, has_keen_eye, has_chlorophyll, has_levitate)) %>% 
  # imputing weight
  step_impute_linear(weight_kg, impute_with = imp_vars(base_total, base_happiness, experience_growth, type1, generation, is_legendary, has_sturdy, has_swift_swim, has_keen_eye, has_chlorophyll, has_levitate)) %>% 
  # Only prioritizing top types of Pokemon
  step_other(type1) %>% 
  # dummy coding nominal variables
  step_dummy(generation, is_legendary, type1, has_sturdy, has_swift_swim, has_keen_eye, has_chlorophyll, has_levitate) %>% 
  # normalizing
  step_center(all_predictors()) %>% 
  step_scale(all_predictors())
```

```{r}
# Creating folds
pokemon_folds <- vfold_cv(pokemon_train, v = 10, strata = capture_rate)
```

### Linear Regression 

```{r}
# Linear regression 
lm_model <- linear_reg() %>% 
  set_engine("lm")

lm_workflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(pokemon_recipe)
```

```{r}
# Fitting the models
lm_fit <- fit_resamples(lm_workflow, resamples = pokemon_folds)

# Save
write_rds(lm_fit, file = "lm_final.rds")
```

```{r}
lm_final_fit <- read_rds(file = "lm_final.rds")

collect_metrics(lm_final_fit)
```

### Polynomial Regression  

### Ridge Regression   
```{r}
ridge_lasso_recipe <- pokemon_recipe %>% 
  step_novel(all_nominal_predictors()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())

ridge_spec <- linear_reg(mixture = 0, penalty = tune()) %>% 
  set_mode("regression") %>% 
  set_engine("glmnet")

ridge_workflow <- workflow() %>% 
  add_recipe(pokemon_recipe) %>% 
  add_model(ridge_spec)

penalty_grid <- grid_regular(penalty(range = c(-5,5)), levels = 50)

ridge_tune <- tune_grid(
  ridge_workflow,
  resamples = pokemon_folds,
  grid = penalty_grid
)

write_rds(ridge_tune, file = "ridge.rds")
```
```{r}
ridge_tune <- read_rds(file = "ridge.rds")

autoplot(ridge_tune)
```

```{r}
best_penalty <- select_best(ridge_tune, metric = 'rmse')

ridge_final <- finalize_workflow(ridge_workflow, best_penalty)
ridge_final_fit <- fit_resamples(ridge_final, resamples = pokemon_folds)

write_rds(ridge_final_fit, file = "ridge_final.rds")

ridge_final_fit <- read_rds(file = "ridge_final.rds")

collect_metrics(ridge_final_fit)
```

### Lasso Regression 
```{r}
lasso_spec <- 
  linear_reg(penalty = tune(), mixture = 1) %>% 
  set_mode("regression") %>% 
  set_engine("glmnet") 

lasso_workflow <- workflow() %>% 
  add_recipe(ridge_lasso_recipe) %>% 
  add_model(lasso_spec)

lasso_tune <- tune_grid(
  lasso_workflow,
  resamples = pokemon_folds,
  grid = penalty_grid
)

write_rds(lasso_tune, file = "lasso.rds")

lasso_tune <- read_rds(file = "lasso.rds")
```

```{r}
autoplot(lasso_tune)
```

```{r}
best_lasso_penalty <- select_best(tune_res2, metric = "rmse")
lasso_final <- finalize_workflow(lasso_workflow, best_lasso_penalty)
lasso_final_fit <- fit_resamples(lasso_final, resamples = pokemon_folds)

write_rds(lasso_final_fit, file = "lasso_final.rds")

lasso_final_fit <- read_rds(file = "lasso_final.rds")

```

```{r}
collect_metrics(lasso_final_fit)
```


```{r, message = FALSE, warning = FALSE}
poly_rec <- pokemon_recipe %>% 
  step_poly(base_total, base_happiness, experience_growth, height_m, percentage_male, weight_kg, degree = tune())

#ggplot(pokemon_train, aes(y = type1)) + geom_bar()


#step_poly(sp_attack, degree = 2) %>% 
 # step_poly(defense, degree = 2) %>% 
  #step_poly(sp_defense, degree = 2) %>% 
#  step_poly(hp, degree = 2) %>% 
 # step_poly(speed, degree = 2)

poly_spec <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

poly_wf <- workflow() %>% 
  add_model(poly_spec) %>% 
  add_recipe(poly_rec)

degree_grid <- grid_regular(degree(range = c(1,5)), levels = 5)

poly_tuned <- tune_grid(
  poly_wf,
  resamples = pokemon_folds,
  grid = degree_grid
)

write_rds(poly_tuned, file = "poly.rds")
poly_tuned <- read_rds(file = "poly.rds")

autoplot(poly_tuned)
```

```{r}
best_poly<- select_best(poly_tuned, metric = "rmse")
poly_final <- finalize_workflow(poly_wf, best_poly)
poly_final_fit <- fit_resamples(poly_final, resamples = pokemon_folds)

write_rds(poly_final_fit, file = "poly_final.rds")

poly_final_fit <- read_rds(file = "poly_final.rds")

collect_metrics(poly_final_fit)
```



### KNN  
```{r, warning=FALSE}
knn_model <- nearest_neighbor(
  neighbors = tune(),
  mode = "regression") %>% 
  set_engine("kknn") 

knn_workflow <- workflow() %>% 
  add_model(knn_model) %>% 
  add_recipe(pokemon_recipe)

knn_grid <- grid_regular(neighbors(range = c(1,15)), levels = 5)

knn_tune <- tune_grid(
    knn_workflow,
    resamples = pokemon_folds,
    grid = knn_grid
  )

write_rds(knn_tune, file = "knn.rds")

knn_tune <- read_rds(file = "knn.rds")

```

```{r}
autoplot(knn_tune)
```


```{r}
best_knn <- select_best(knn_tune, metric = "rmse")
knn_final <- finalize_workflow(knn_workflow, best_knn)
knn_final_fit <- fit_resamples(knn_final, resamples = pokemon_folds)

write_rds(knn_final_fit, file = "knn_final.rds")

knn_final_fit <- read_rds(file = "knn_final.rds")
```


```{r}
collect_metrics(knn_final_fit)
```

### Elastic Net  

```{r, warning = FALSE, message = FALSE}
elastic_spec <- 
  linear_reg(penalty = tune(), mixture = tune()) %>% 
  set_mode("regression") %>% 
  set_engine("glmnet") 

elastic_workflow <- workflow() %>% 
  add_recipe(pokemon_recipe) %>% 
  add_model(elastic_spec)

elastic_grid <- grid_regular(penalty(range = c(-5, 5)), mixture(range = c(0,1)), levels = 10)

elastic_tune <- tune_grid(
  elastic_workflow,
  resamples = pokemon_folds,
  grid = elastic_grid
)

write_rds(elastic_tune, file = "elastic.rds")
```

```{r}
elastic_tune <- read_rds(file = "elastic.rds")

autoplot(elastic_tune)
```

```{r}
# Finding roc_auc of best performing random forest model on folds
elastic_best_rmse <- elastic_tune %>% 
  collect_metrics() %>% 
  arrange(mean)  %>% 
  slice(73)

elastic_best_rmse
```


```{r}
best_elastic <- select_best(elastic_tune, metric = "rmse")
elastic_final <- finalize_workflow(elastic_workflow, best_elastic)
elastic_final_fit <- fit_resamples(elastic_final, resamples = pokemon_folds)

write_rds(elastic_final_fit, file = "elastic_final.rds")

elastic_final_fit <- read_rds(file = "elastic_final.rds")

collect_metrics(elastic_final_fit)
```

```{r}
# Setting up random forest model with specified tuning parameters and engine
rf_spec <- rand_forest(mtry = tune(), trees = tune(), min_n = tune()) %>% 
  set_engine("ranger", importance = "impurity") %>% 
  set_mode("regression")

# Setting up random forest workflow
rf_workflow <- workflow() %>% 
  add_recipe(pokemon_recipe) %>% 
  add_model(rf_spec)

# Creating a regular grid with 8 levels each
rf_parameter_grid <- grid_regular(mtry(range = c(1, 14)), trees(range = c(200,1000)), min_n(range = c(5,20)), levels = 8)
```

```{r, eval = FALSE}
# Tuning the model with roc_auc as a metric
rf_tune_res <- tune_grid(
  rf_workflow,
  resamples = pokemon_folds,
  grid = rf_parameter_grid
)

# Saving the fit
write_rds(rf_tune_res, file = "rf.rds")
```


```{r}
# Loading in the random forest
rf_tuned <- read_rds(file = "rf.rds")

# Producing autoplot of results
autoplot(rf_tuned, metric = 'rmse')
```

```{r}
# Finding roc_auc of best performing random forest model on folds
rf_best_rmse <- rf_tuned %>% 
  collect_metrics() %>% 
  arrange(mean) %>% 
  slice(513)

rf_best_rmse
```

```{r}
best_rf <- select_best(rf_tuned)
rf_final_workflow <- finalize_workflow(rf_workflow, best_rf)
rf_final_fit <- fit_resamples(rf_final_workflow, resamples = pokemon_folds)

write_rds(rf_final_fit, file = "rf_final.rds")

rf_final_fit <- read_rds(file = "rf_final.rds")

collect_metrics(rf_final_fit) %>% slice(1)
```


```{r}
best_rf2 <- select_best(rf_tuned)
rf_final_workflow2 <- finalize_workflow(rf_workflow, best_rf)
rf_final_fit2 <- fit(rf_final_workflow, data = pokemon_train)

rf_final_fit2 %>% 
  extract_fit_engine() %>% 
  vip()
```

### BOOSTED TREE
```{r}
# Setting up boosted tree model
boosted_spec <- boost_tree(trees = tune(),
                          learn_rate = tune(),
                          min_n = tune()) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

# Setting up boosted trees workflow
boosted_workflow <- workflow() %>% 
  add_recipe(pokemon_recipe) %>% 
  add_model(boosted_spec)

# Creating regular grid
boosted_grid <- grid_regular(trees(range = c(5, 200)), learn_rate(range = c(0.01,0.1), trans = identity_trans()), min_n(range = c(40, 60)), levels = 5)
```

```{r, eval = FALSE}
# Tuning and specifying roc_auc
boosted_tune_res <- tune_grid(
  boosted_workflow,
  resamples = pokemon_folds,
  grid = boosted_grid
)

# Saving the fit
write_rds(boosted_tune_res, file = "boosted.rds")
```

```{r}
# Loading the fit
boosted_tuned <- read_rds(file = "boosted.rds")

# Printing autoplot of results
autoplot(boosted_tuned, metric = 'rmse')
```

```{r}
# Finding roc_auc of best performing boosted tree model on folds
boosted_best_rmse <- boosted_tuned %>% 
  collect_metrics() %>% 
  arrange(mean) %>% 
  slice(126)

boosted_best_rmse
```

```{r, eval = FALSE, warning = FALSE}
# Elastic
elastic_tuned <- read_rds(file = "elastic_tune.rds")

# Fitting best random forest model to the folds
best_elastic <- select_best(elastic_tuned)
elastic_final_workflow <- finalize_workflow(elastic_workflow, best_elastic)
elastic_final_fit <- fit_resamples(elastic_final_workflow, resamples = pokemon_folds)

# Save
write_rds(rf_final_fit, file = "elastic_final.rds")

# Polynomial Regression
poly_tuned <- read_rds(file = "poly_tuned.rds")

# Fitting best random forest model to the folds
best_poly <- select_best(poly_tuned)
poly_final_workflow <- finalize_workflow(poly_wf, best_poly)
poly_final_fit <- fit_resamples(poly_final_workflow, resamples = pokemon_folds)

# Save
write_rds(rf_final_fit, file = "poly_final.rds")

# Random Forest
rf_tuned <- read_rds(file = "rf.rds")

# Fitting best random forest model to the folds
best_rf <- select_best(rf_tuned)
rf_final_workflow <- finalize_workflow(rf_workflow, best_rf)
rf_final_fit <- fit_resamples(rf_final_workflow, resamples = pokemon_folds)

# Save
write_rds(rf_final_fit, file = "rf_final.rds")


# Boosting
boosted_tuned <- read_rds(file = "boosted.rds")

# Fitting best boosted trees model to the folds
best_boosted <- select_best(boosted_tuned)
boosted_final_workflow <- finalize_workflow(boosted_workflow, best_boosted)
boosted_final_fit <- fit_resamples(boosted_final_workflow, resamples = pokemon_folds)

# Save
write_rds(boosted_final_fit, file = "boosted_final.rds")
```

```{r}

```









