```{r}
# Loading all necessary packages
library(tidyverse)
library(dplyr)
library(tidymodels)
library(readr)
library(kknn)
library(janitor)
library(ISLR)
library(discrim)
library(poissonreg)
library(glmnet)
library(corrr)
library(corrplot)
library(randomForest)
library(xgboost)
library(rpart.plot)
library(vip)
library(ranger)
# Assigning the data to a variable
pokemon <- read_csv("data/pokemon.csv")
tidymodels_prefer()
set.seed(0124)
```



```{r}
pokemon_data <- read_csv("pokemon_final.csv")
head(pokemon_data)
```

```{r}
# Changing categorical predictors to factors
pokemon_data$type1 <- as.factor(pokemon_data$type1)
pokemon_data$generation <- as.factor(pokemon_data$generation)
pokemon_data$is_legendary <- as.factor(pokemon_data$is_legendary)
pokemon_data$has_sturdy <- as.factor(pokemon_data$has_sturdy)
pokemon_data$has_swift_swim <- as.factor(pokemon_data$has_swift_swim)
pokemon_data$has_keen_eye <- as.factor(pokemon_data$has_keen_eye)
pokemon_data$has_chlorophyll <- as.factor(pokemon_data$has_chlorophyll)
pokemon_data$has_levitate <- as.factor(pokemon_data$has_levitate)
```


```{r}
# Splitting the data
pokemon_split <- initial_split(pokemon_data, prop = 0.7, strata = capture_rate)
pokemon_train <- training(pokemon_split)
pokemon_test <- testing(pokemon_split)

#sd(pokemon_train$capture_rate)
```

```{r}
# Creating recipe
pokemon_recipe <- recipe(capture_rate ~ base_total + is_legendary, data = pokemon_train) %>% 
  # dummy coding nominal variables
  step_dummy(is_legendary) %>% 
  # normalizing
  step_center(all_predictors()) %>% 
  step_scale(all_predictors())
```

```{r}
# Creating folds
pokemon_folds <- vfold_cv(pokemon_train, v = 10, strata = capture_rate)
```

```{r}
# Linear regression 
lm_model <- linear_reg() %>% 
  set_engine("lm")

lm_workflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(pokemon_recipe)
```

```{r}
# Fitting the models
lm_fit <- fit_resamples(lm_workflow, resamples = pokemon_folds)
```

```{r}
collect_metrics(lm_fit)
```

```{r, message = FALSE, warning = FALSE}
poly_rec <- pokemon_recipe %>% 
  step_poly(base_total, base_happiness, experience_growth, height_m, percentage_male, weight_kg, degree = tune())

#ggplot(pokemon_train, aes(y = type1)) + geom_bar()

#step_poly(sp_attack, degree = 2) %>% 
 # step_poly(defense, degree = 2) %>% 
  #step_poly(sp_defense, degree = 2) %>% 
#  step_poly(hp, degree = 2) %>% 
 # step_poly(speed, degree = 2)

lm_spec <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

poly_wf <- workflow() %>% 
  add_model(lm_spec) %>% 
  add_recipe(poly_rec)

degree_grid <- grid_regular(degree(range = c(1,6)), levels = 6)

tune_res3 <- tune_grid(
  poly_wf,
  resamples = pokemon_folds,
  grid = degree_grid
)
autoplot(tune_res3)
```

```{r}
best_poly<- select_best(tune_res3, metric = "rmse")
poly_final <- finalize_workflow(poly_wf, best_poly)
poly_final_fit <- fit_resamples(poly_final, resamples = pokemon_folds)

collect_metrics(poly_final_fit)
```

```{r}
# Setting up boosted tree model
boosted_spec <- boost_tree(trees = tune(),
                          learn_rate = tune(),
                          min_n = tune()) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

# Setting up boosted trees workflow
boosted_workflow <- workflow() %>% 
  add_recipe(pokemon_recipe) %>% 
  add_model(boosted_spec)

# Creating regular grid
boosted_grid <- grid_regular(trees(range = c(5, 200)), learn_rate(range = c(0.1,1), trans = identity_trans()), min_n(range = c(40, 60)), levels = 2)
```

```{r, eval = FALSE}
# Tuning and specifying roc_auc
boosted_tune_res <- tune_grid(
  boosted_workflow,
  resamples = pokemon_folds,
  grid = boosted_grid
)

# Saving the fit
write_rds(boosted_tune_res, file = "boosted_3.rds")
```

```{r}
# Loading the fit
boosted_tuned <- read_rds(file = "boosted_3.rds")

# Printing autoplot of results
autoplot(boosted_tuned)
```

```{r}
# Finding roc_auc of best performing boosted tree model on folds
boosted_best_roc_auc <- boosted_tuned %>% 
  collect_metrics() %>% 
  arrange(desc(mean)) %>% 
  head(1)

boosted_best_roc_auc
```








